export { default as HomePage } from './Home'
export { default as LeadsPage } from './Leads'
export { default as LoginPage } from './Login'
export { default as ProfilePage } from './Profile'
export { default as RegistrationPage } from './Registration'
